### ISSUE TITLE
Update Formula for Monster's rolled HP

### ISSUE THREAD

**Issue by gatesvp** [Muttley/foundryvtt-shadowdark#570] opened 2023-11-02 02:21 UTC
### Current Behaviour
Monsters are assumed to have a CON modifier of 1 when rolling for HP.

That behaviour comes from the following snippet, and is implemented by [this line of code](https://github.com/Muttley/foundryvtt-shadowdark/blob/0c2a17f86c9e01d6e4298dd7a33b9280ca4ee1b8/system/src/documents/ActorSD.mjs#L1163)
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/f0e823aa-77ce-4c19-8787-07d427baf6bf)

### Expected Behaviour
Monster HP die rolls apply their CON modifier to each die, but a single die must have a value of at least 1.

Based on [the following discussion](https://discord.com/channels/558029475837902851/821568382952407070/1024351246427095171).
![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/319590/fad0ae2b-83d2-476d-a46f-1755d67103ee)

### Some examples

Apprentice is a LV 1 monster with a CON modifier of -1, and a total HP value of 3.
Archmage is a LV 10 monster with a CON modifier of -1, and a total HP value of 44.
Acolyte is also a LV 1 monster with a CON modifier of +0, and has a total HP value of 4.
Badger is also a LV 1 monster with a CON modifier of +1, and has a total HP value of 5.

**Comment by Muttley** [comment] 2023-11-02 03:32
Duplicate of #568

**Closed by Muttley** 2023-11-02 03:32 UTC
