### ISSUE TITLE
Disadvantage

### ISSUE THREAD

**Issue by teacherx333** [Muttley/foundryvtt-shadowdark#850] opened 2024-08-15 02:29 UTC
Similar to Advantage, can we have "disadvantage" in the drop down to create - effects, items, curses that would give disadvantage.

1) disadvantage overall
2) disadvantage only to the item created, like a weapon, talent, belt, helmet, etc.

**Comment by Muttley** [comment] 2024-08-28 08:07
Closed as duplicate of #606

**Closed by Muttley** 2024-08-28 08:07 UTC
