### ISSUE TITLE
[BUG] +2 HP bonus for Stout talent not included in initial HP

### ISSUE THREAD

**Issue by johncarney** [Muttley/foundryvtt-shadowdark#889] opened 2024-09-09 04:11 UTC
When creating a new Dwarf character, it rolls and calculates the maximum HP correctly, but appears not to include the Stout bonus in the initial HP. That is, the HP section of the character sheet will show "2 / 4," for example. This happens when generating both level 0 and level 1 characters. Obviously this can be corrected easily enough manually.

https://github.com/user-attachments/assets/144db014-cb77-470e-be22-1be3d0bef2e4

**Comment by johncarney** [comment] 2024-09-09 04:34
PS. This is on Shadowdark v3.1.1. Also, this is not an issue for characters imported from ShadowDarklings.

**Comment by Muttley** [comment] 2024-09-09 08:55
Closing as duplicate of #888

**Closed by Muttley** 2024-09-09 08:55 UTC
