### ISSUE TITLE
Button to apply damage to target(s)

### ISSUE THREAD

**Issue by Delgored** [Muttley/foundryvtt-shadowdark#536] opened 2023-10-17 01:35 UTC
I was wondering how hard it would be to add a button that will allow the damage to be dealt to the target (marked with T)

![image](https://github.com/Muttley/foundryvtt-shadowdark/assets/148171166/2a52d1b9-55d4-4653-9bc7-f0c72e8e1261)

Just under it "apply damage to target" that the player selected.

**Comment by Muttley** [comment] 2023-10-17 10:48
Duplicate of #277

**Closed by Muttley** 2023-10-17 10:48 UTC
