### ISSUE TITLE
Feature Request: Add Focus Check to Spells

### ISSUE THREAD

**Issue by accerak** [Muttley/foundryvtt-shadowdark#851] opened 2024-08-24 12:42 UTC
Please consider adding an icon to the character sheet spells or a button in the spell casting check dialog so that a focus check could be performed rather than just a check to cast the spell.  Right now, the easiest way to perform a focus check is to click the "cast spell" button, but if the check fails, then the spell ends up showing as lost in the interface.  Just a quality of life thing to avoid having to go back and un-lose the spell manually.

**Comment by TheBrianFactor** [comment] 2024-08-24 15:43
This is already included in the developer's workflow as a quality of life improvement to be implemented:

https://github.com/Muttley/foundryvtt-shadowdark/issues/205

**Comment by Muttley** [comment] 2024-08-25 00:16
Closing as duplicate of #205

**Closed by Muttley** 2024-08-25 00:16 UTC
