### ISSUE TITLE
Incorrect display of attack bonuses

### ISSUE THREAD

**Issue by ZurielRedux** [Muttley/foundryvtt-shadowdark#153] opened 2023-03-23 20:36 UTC
![image](https://user-images.githubusercontent.com/3752090/227348650-b72313bf-c85c-4bdf-93b2-fb4905e18d1c.png)

The bonus for the longbow is shown as +4 here, but it should be +5 for a 1st level elf fighter here(+3 dex, +1 elf ancestory, +1 weapon mastery) , and when I upped my level 3 it should be +6 but it doesnt change, it is still +4. The rolls work correctly, it is just the display on the character sheet that is off.

**Comment by Muttley** [comment] 2023-03-24 00:44
Duplicate of #157

**Closed by Muttley** 2023-03-24 00:44 UTC
Labels: bug
